
# Vagrant.configure("2") do |config|
#   config.vm.box = "hashicorp/bionic64"
#   config.vm.network "public_network", ip: "192.168.0.17"
# end


servers=[
  {
    :hostname => "manager",
    :ip => "192.168.100.10",
    :box => "hashicorp/bionic64",
    :ram => 1024,
    :cpu => 2
  },
  {
    :hostname => "worker-1",
    :ip => "192.168.100.11",
    :box => "hashicorp/bionic64",
    :ram => 1024,
    :cpu => 2
  },
  {
    :hostname => "worker-2",
    :ip => "192.168.100.12",
    :box => "hashicorp/bionic64",
    :ram => 1024,
    :cpu => 2
  }
]
Vagrant.configure(2) do |config|
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      # if machine[:hostname] == "manager"
      config.vm.synced_folder "main/", "/main"
      # end
      node.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
      end
    end
  end
end